# Generated by Django 4.2.16 on 2024-12-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('promoter', 'Promoter/Venue'), ('artist', 'Band/Artist'), ('attendee', 'Attendee')], max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
