# Generated by Django 4.2.16 on 2025-01-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabal', '0002_artist_attendee_event_venue_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='past_events',
            field=models.ManyToManyField(related_name='historical_events', to='cabal.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='eventstatistics',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='eventstatistics',
            name='tickets_sold',
            field=models.IntegerField(default=0),
        ),
    ]
