# Generated by Django 4.2.16 on 2025-01-22 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabal', '0003_alter_artist_past_events_alter_event_ticket_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='past_events',
            field=models.ManyToManyField(blank=True, related_name='historical_events', to='cabal.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='events', to='cabal.artist'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to=settings.AUTH_USER_MODEL),
        ),
    ]
